# Generated by Django 3.0.3 on 2020-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='stripe_is',
            new_name='stripe_id',
        ),
    ]
