# Generated by Django 3.0.3 on 2020-04-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200409_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='biling_profile',
            new_name='billing_profile',
        ),
    ]
